import DateList from '@/components/DateListOld';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useState, useEffect } from 'react';

const Home: NextPage = () => {
  const loadDate = new Date();
  // const lastUpdated = loadDate.toLocaleString('en-US', {
  //   hour: 'numeric',
  //   minute: 'numeric'
  // });

  // console.log(lastUpdated);

  const [lastUpdated, setLastUpdated] = useState(
    loadDate.toLocaleString('en-US', {
      hour: 'numeric',
      minute: 'numeric'
    })
  );

  const todayFormat = loadDate.toLocaleString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
  const dayOfWeek = loadDate.toLocaleString('en-US', { weekday: 'long' });

  const countdown = {
    Monday: {
      items: [
        { name: 'CSE 174', time: '10:05' },
        { name: 'MKT 315', time: '13:15' }
      ]
    },
    Tuesday: {
      items: [
        { name: 'MKT 395', time: '10:05' },
        { name: 'MGT 302', time: '14:50' }
      ]
    },
    Wednesday: {},
    Thursday: {},
    Friday: {},
    Saturday: {},
    Sunday: {}
  };

  // DateList({ countdown, weekDay: 'Monday' });

  console.log(countdown);
  countdown.Monday.items.map((item) => console.log(item.name));

  // useEffect(() => {
  //   const interval = setInterval(() => {
  //     const loadDate = new Date();

  //     setLastUpdated(
  //       loadDate.toLocaleString('en-US', {
  //         hour: 'numeric',
  //         minute: 'numeric',
  //         second: 'numeric'
  //       })
  //     );
  //   }, 1000);
  //   return () => clearInterval(interval);
  // }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-6">
        <div className="prose">
          <h1 className="m-0">{todayFormat}</h1>
          <p className="mt-0 mb-6">Last Updated: {lastUpdated}</p>

          <DateList
            countdown={countdown}
            // weekDay={dayOfWeek}
            loadDate={loadDate}
          />
        </div>
      </main>
    </div>
  );
};

export default Home;
